stages:
  - build
  - deploy

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t firefox-multiuser-manager:latest .
    - docker tag firefox-multiuser-manager:latest $CI_REGISTRY_IMAGE/firefox-multiuser-manager:latest
    - docker push $CI_REGISTRY_IMAGE/firefox-multiuser-manager:latest

deploy:
  stage: deploy
  only:
    - main
  script:
    - docker-compose down
    - docker-compose up -d
