version: "3.8"

services:
  firefox-manager:
    image: "firefox-multiuser-manager:latest"
    container_name: firefox-manager
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
